### ISSUE TITLE
Envrionmental Variables

### ISSUE THREAD

**Issue by cancan101** [leolara/docker-woocommerce#1]
What is the point of these environmental variables: https://github.com/leolara/docker-woocommerce/blob/5c82f316424c25a5e62beeee57e910f6128d4ed0/Dockerfile#L3 ?

**Comment by leolara** [comment]
Very nice to meet you @cancan101 

Mainly, I am doing like here: https://github.com/docker-library/wordpress/blob/master/fpm/Dockerfile#L11

I think this allows to enable to write scripts that run in a container based on this image, that knows the versions.

A step further would be also to use it like in the Dockerfile of wordpress, to parametrise the download. But, as I am not updating this so frequently I didn´t do it.

For example, using this environmental variables you could write a script  that install additional plugins and that decides the versions based on woocommerce version.

**Comment by cancan101** [comment]
Right so it looks like the Dockerfile you reference does use the env variable for the download.

Why do you they / you have variables though?

**Comment by leolara** [comment]
Hi @cancan101 I do not have much time, so could you be more specific with what is the issue please?

The Dockerfile I reference use the env variable for the download, but there are other env variable that is not used in the Dockerfile itself.

If you think it would be better to use the env variable in the download, please do a pull request.

Basically, we are using env variables as the parent Dockerfile.

**Comment by leolara** [comment]
I close, please if there is an issue, create a new ticket explaining the problem.
